name: Snap Build

on:
  push:
  pull_request:
    types: [opened, reopened]    
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        arch: [amd64, arm64]
        include:
          - arch: amd64
            runner: ubuntu-24.04
          - arch: arm64
            runner: ubuntu-24.04-arm
    runs-on: ${{ matrix.runner }}
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        fetch-tags: true
    - uses: canonical/action-build@v1.3.0
      id: build
    - uses: actions/upload-artifact@v4
      with:
        name: snap-${{ matrix.arch }}
        path: ${{ steps.build.outputs.snap }}
        retention-days: 5
